# ====================================
#    APPLICATION
# ====================================
spring.application.name=notification-service
server.port=8089

# ====================================
#    MAIL CONFIGURATION
# ====================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ce8b85c52e2eda
spring.mail.password=0efa2d52ac28f1

# ====================================
#    KAFKA CONSUMER CONFIGURATION
# ====================================
spring.kafka.bootstrap-servers=broker:29092
spring.kafka.consumer.group-id=NotificationService
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# Confluent Schema Registry
spring.kafka.consumer.properties.schema.registry.url=http://schema-registry:8081
spring.kafka.consumer.properties.specific.avro.reader=true

# ====================================
#    LOGGING
# ====================================
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

logging.pattern.console={\
"time":"%d{yyyy-MM-dd HH:mm:ss}",\
"level":"%level",\
"thread":"%thread",\
"logger":"%logger",\
"service":"${spring.application.name}",\
"message":"%msg"\
}

# ====================================
#    ACTUATOR / PROMETHEUS / TRACING
# ====================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
management.health.circuitbreakers.enabled=true
